project_id = "nvtxjskwskwxqsaifneo"

[functions.octopart-search]
verify_jwt = false

[functions.digikey-search]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.seo-snapshot]
verify_jwt = false